version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  verify:
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '18'
          pkg-manager: npm
